# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/
# Compatible with golangci-lint v1.x

run:
  timeout: 5m
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  disable-all: true
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Examine Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused code
    
    # Additional security & quality linters
    - bodyclose     # Check HTTP response body is closed
    - copyloopvar   # Detect loop variable issues
    - dupl          # Code duplication
    - errorlint     # Error wrapping issues
    - goconst       # Find repeated strings that could be constants
    - gocritic      # Opinionated linter
    - gocyclo       # Cyclomatic complexity
    - gofmt         # Check formatting
    - goimports     # Check import order
    - gosec         # Security issues
    - misspell      # Spelling mistakes
    - nakedret      # Naked returns in long functions
    - nilerr        # nil error returns
    - nolintlint    # Check nolint directives
    - revive        # Fast, configurable linter
    - unconvert     # Unnecessary type conversions
    - unparam       # Unused function parameters
    - whitespace    # Whitespace issues

linters-settings:
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 150
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam  # Allow large structs by value
  
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: indent-error-flow
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: var-declaration
      - name: var-naming
  
  gosec:
    excludes:
      - G104  # Audit errors not checked (too noisy)
      - G304  # File inclusion via variable (needed for config)

issues:
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    
    # Exclude some linters from running on generated files
    - path: \.pb\.go
      linters:
        - all

  max-issues-per-linter: 50
  max-same-issues: 10
