apiVersion: v2
dependencies:
  - name: agis-bot
    repository: http://chartmuseum.chartmuseum.svc.cluster.local:8080
    version: 0.0.1-rc.b2afb3c
description: agis-bot example application
name: agis-bot
type: application
version: 1.0.0
