apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
spec:
  entrypoint: main
  serviceAccountName: argo-server
  arguments:
    parameters:
      - name: appName
      - name: branch
      - name: clusterName
      - name: environment
      - name: gitUrlNoProtocol
      - name: shortSha
  templates:
    - name: main
      steps:
        - - name: checkout
            templateRef:
              name: cwft-git
              template: checkout-with-gitops-ssh
              clusterScope: true
            arguments:
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: branch
                  value: '{{workflow.parameters.branch}}'
                - name: gitUrlNoProtocol
                  value: '{{workflow.parameters.gitUrlNoProtocol}}'
        - - name: get-initial-chart-version
            templateRef:
              name: cwft-helm
              template: get-chart-version
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.checkout.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: chartDir
                  value: 'charts/{{workflow.parameters.appName}}'
        - - name: set-environment-version
            templateRef:
              name: cwft-helm
              template: set-environment-version
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.checkout.outputs.artifacts.repo-source}}'
              parameters:
                - name: fullChartPath
                  value: 'registry/clusters/wtg-eu-west/components/{{workflow.parameters.environment}}/{{workflow.parameters.appName}}/values.yaml'
                - name: chartVersion
                  value: '{{steps.get-initial-chart-version.outputs.result}}-rc.{{workflow.parameters.shortSha}}'
                - name: environment
                  value: '{{workflow.parameters.environment}}'
        - - name: commit
            templateRef:
              name: cwft-git
              template: pull-commit-push-ssh
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-environment-version.outputs.artifacts.repo-source}}'
              parameters:
                - name: repoName
                  value: 'gitops'
                - name: gitUrlNoProtocol
                  value: '{{workflow.parameters.gitUrlNoProtocol}}'
                - name: commitMessage
                  value: 'setting {{workflow.parameters.appName}} {{workflow.parameters.environment}} to chart version {{steps.get-initial-chart-version.outputs.result}}-rc.{{workflow.parameters.shortSha}}'
        - - name: notify-success
            templateRef:
              name: cwft-discord-notifications
              template: notify-discord-success
              clusterScope: true
            arguments:
              parameters:
                - name: message
                  value: '🚀 {{workflow.parameters.appName}} successfully deployed to {{workflow.parameters.environment}}'
                - name: workflowName
                  value: '{{workflow.name}}'
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: environment
                  value: '{{workflow.parameters.environment}}'
                - name: commitSha
                  value: '{{workflow.parameters.shortSha}}'
  onExit: notify-on-failure
  templates:
    - name: notify-on-failure
      templateRef:
        name: cwft-discord-notifications
        template: notify-discord-failure
        clusterScope: true
      arguments:
        parameters:
          - name: message
            value: '❌ {{workflow.parameters.appName}} deployment failed on {{workflow.parameters.environment}}'
          - name: workflowName
            value: '{{workflow.name}}'
          - name: appName
            value: '{{workflow.parameters.appName}}'
          - name: environment
            value: '{{workflow.parameters.environment}}'
          - name: commitSha
            value: '{{workflow.parameters.shortSha}}'
          - name: errorMessage
            value: '{{workflow.status}}'
