apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: agis-bot-deploy-
spec:
  entrypoint: deploy
  templates:
    - name: deploy
      steps:
        - - name: update-gitops-repo
            template: update-gitops-repo
  templates:
    - name: update-gitops-repo
      container:
        image: alpine/git:2.43.0
        command: [sh, -c]
        args:
          - |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "GitHub Actions"
            git clone $GITOPS_REPO_URL repo
            cd repo
            # Update the chart version for the environment
            yq e -i '.spec.source.targetRevision = "{{workflow.parameters.shortSha}}"' registry/clusters/wtg-eu-west/agis-bot-{{workflow.parameters.environment}}.yaml
            git add .
            git commit -m "Update agis-bot chart version to {{workflow.parameters.shortSha}} for {{workflow.parameters.environment}}"
            git push
        env:
          - name: GITOPS_REPO_URL
            valueFrom:
              secretKeyRef:
                name: gitops-creds
                key: url
          - name: GITOPS_TOKEN
            valueFrom:
              secretKeyRef:
                name: gitops-creds
                key: token
