apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: agis-bot-publish-
spec:
  entrypoint: publish
  templates:
    - name: publish
      steps:
        - - name: build-and-push-image
            template: build-and-push-image
        - - name: package-and-push-chart
            template: package-and-push-chart
  templates:
    - name: build-and-push-image
      container:
        image: docker:24
        command: [sh, -c]
        args:
          - |
            docker login ghcr.io -u $GITHUB_ACTOR -p $GITHUB_TOKEN
            docker build -t ghcr.io/wethegamers/agis-bot:{{workflow.parameters.shortSha}} .
            docker push ghcr.io/wethegamers/agis-bot:{{workflow.parameters.shortSha}}
        env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token
                key: token
    - name: package-and-push-chart
      container:
        image: alpine/helm:3.13.2
        command: [sh, -c]
        args:
          - |
            helm package ./charts/agis-bot --version {{workflow.parameters.shortSha}}
            curl --data-binary "@agis-bot-{{workflow.parameters.shortSha}}.tgz" -u "$CHARTMUSEUM_USER:$CHARTMUSEUM_PASS" "$CHARTMUSEUM_URL/api/charts?force=true"
        env:
          - name: CHARTMUSEUM_USER
            valueFrom:
              secretKeyRef:
                name: chartmuseum-creds
                key: username
          - name: CHARTMUSEUM_PASS
            valueFrom:
              secretKeyRef:
                name: chartmuseum-creds
                key: password
          - name: CHARTMUSEUM_URL
            valueFrom:
              secretKeyRef:
                name: chartmuseum-creds
                key: url
